apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform.yaml
  - runtime-config.yaml
  - identity-data.yaml
  - keycloak.yaml
  - backend.yaml
  - apisix.yaml
  - tls.yaml
  - monitoring.yaml
